### ISSUE TITLE
dm me

### ISSUE THREAD

**Issue by Lxxxst** [z-jxy/instacheck#1]
i have a question can u dm on discord Lust#6741

**Comment by z-jxy** [comment]
why not ask here?

**Comment by Lxxxst** [comment]
i want to talk to u in dm for something i got a code request could u add me

**Comment by Lxxxst** [comment]
i can pay

**Comment by z-jxy** [comment]
not sure what u mean by code request

**Comment by z-jxy** [comment]
you mean code that you wanted to contribute to the repo?

**Comment by Lxxxst** [comment]
I had a request for priv programming, dm i can pay u to make it

**Comment by Lxxxst** [comment]
so can u dm

**Comment by Lxxxst** [comment]
like i need smth coded, i wanna see if u are able to do it, i'm gonna pay
